[IOPLT-571] Implement get activation job
pagopa/trial-system pull request #85
Opened 2024-06-18 12:27 UTC by kin0992

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] I have committed only changes relevant to the task.
- [ ] I have minimized the number of changes.
- [ ] My changes are about only one task or issue.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-18 12:27 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/cosmosdb/__tests__/activation-job.test.ts
> +    it('should insert the item without error', async () => {
**note**: just fixed a typo

2024-06-19 10:19 UTC, datalek requested changes

2024-06-19 10:19 UTC, datalek commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/get-activation-job.test.ts
> +    expect(await actual.json()).toMatchObject(expectedJson);
**question**: Given that the compiler will produce a type error if the structure does not match, do you think this check makes the code more robust?

2024-06-19 10:19 UTC, datalek commented on apps/functions-subscription/src/adapters/azure/cosmosdb/activation-job.ts
> +      ),
**issue**: I'm not sure if this cause any issues.

```suggestion
        TE.flatMapEither(decodeFromItem(ActivationJobCodec)),
        TE.mapLeft(cosmosErrorToDomainError),
      ),
```

2024-06-19 10:26 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/get-activation-job.test.ts
> +describe('getActivationJob', () => {
```suggestion
describe('makeGetActivationJobHandler', () => {
```

2024-06-19 15:43 UTC, datalek approved these changes
LGTM

2024-06-19 15:45 UTC, merged