[IOPLT-570] Add update activation job
pagopa/trial-system pull request #86
Opened 2024-06-18 14:13 UTC by datalek

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] I have committed only changes relevant to the task.
- [ ] I have minimized the number of changes.
- [ ] My changes are about only one task or issue.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-19 11:07 UTC, kin0992 requested changes

2024-06-19 11:07 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/data.ts
> +    url: 'https://function/trials/{trialId}/activation-jobs/{id}',
**issue**: wrong path according to the OpenAPI
```suggestion
    url: 'https://function/trials/{trialId}/activation-job,
```

2024-06-19 11:07 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts
> +      url: 'https://function/trials/{trialId}/activation-jobs/{id}',
same as above
```suggestion
      url: 'https://function/trials/{trialId}/activation-job',
```

2024-06-19 11:07 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts
> +        id: 'anId',
```suggestion
```

2024-06-19 11:07 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/__tests__/update-activation-job.test.ts
> +    expect(env.insertActivationJob).toBeCalledTimes(0);
```suggestion
    expect(env.updateActivationJob).toBeCalledTimes(0);
```

2024-06-19 11:07 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/functions/update-activation-job.ts
> +    RTE.mapLeft(toHttpProblemJson),
**note**: I think you can do this as well
```suggestion
    RTE.mapBoth(toHttpProblemJson, flow(toActivationJobAPI, H.successJson)),
```

2024-06-19 16:08 UTC, datalek commented on apps/functions-subscription/api/internal.yaml
> +                $ref: '#/components/schemas/ProblemJson'
Done ✅

2024-06-20 07:37 UTC, kin0992 commented on apps/functions-subscription/src/adapters/azure/cosmosdb/activation-job.ts
> +                value: update.usersToActivate,
**issue**: `usersToActivate` is defined as an optional parameter; what happens if that parameter is `undefined`?

2024-06-20 08:25 UTC, merged